=== STECHOQ/etherlab-nodejs/slave-configuration.schema.json
{"$schema":"http://json-schema.org/draft-07/schema","$id":"https://raw.githubusercontent.com/wiki/STECHOQ/etherlab-nodejs/schema/slave-configuration.schema.json","type":"array","title":"SlavesConfiguration","description":"All attached slaves must be defined in here.","items":{"type":"object","title":"Slave","additionalProperties":false,"required":["alias","position","vendor_id","product_code"],"examples":[{"alias":0,"position":0,"vendor_id":"0x00000002","product_code":"0x044c2c52"},{"alias":0,"position":1,"vendor_id":"0x00000002","product_code":"0x18503052","syncs":[{"index":3,"watchdog_enabled":false,"pdos":[{"index":"0x1a00","entries":[{"index":"0x6000","subindex":"0x01","size":16,"add_to_domain":true,"swap_endian":true,"signed":false}]}]}],"parameters":[{"index":"0x8000","subindex":"0x04","size":32,"value":"0x55"}]}],"properties":{"alias":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Slave's alias number (in integer or hexadecimal string).","examples":[0]},"position":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Slave's position relative to master (in integer or hexadecimal string).","examples":[0,1]},"vendor_id":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Slave's vendor id (in integer or hexadecimal string).","examples":["0x00000002",2]},"product_code":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Slave's product code (in integer or hexadecimal string).","examples":["0x0fa43052",262418514]},"syncs":{"type":"array","title":"syncs","description":"SM configurtion. Omit this field if the slave is a bus coupler, such as EK1100","items":{"type":"object","title":"SyncManager","required":["index","pdos"],"examples":[{"index":2,"watchdog_enabled":false,"pdos":[{"index":"0x1600"},{"index":"0x1601"},{"index":"0x1602"},{"index":"0x1603"}]}],"properties":{"index":{"type":"integer","description":"Sync Manager index"},"watchdog_enabled":{"type":"boolean","description":"Watchdog status. If omitted, then it would be treated as false.","default":false},"pdos":{"type":"array","title":"pdos","description":"PDO entries.","items":{"type":"object","title":"PDOEntry","examples":[{"index":"0x1600"},{"index":"0x1a00","entries":[{"index":"0x6000","subindex":"0x01","size":16,"add_to_domain":true,"swap_endian":true,"signed":false}]}],"required":["index"],"properties":{"index":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"PDO CoE index (in integer or hexadecimal string)."},"entries":{"type":"array","title":"sdos","description":"Map PDO from SDO entries.","items":{"type":"object","title":"SDOEntry","examples":[{"index":"0x6000","subindex":"0x01","size":16,"add_to_domain":true,"swap_endian":true,"signed":false}],"required":["index","subindex","size"],"properties":{"index":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"SDO CoE index to be mapped to PDO (in integer or hexadecimal string)."},"subindex":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"SDO CoE subindex to be mapped to PDO (in integer or hexadecimal string)."},"size":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Size in bit (in integer or hexadecimal string)."},"add_to_domain":{"type":"boolean","description":"Add to Domain or not.","default":false},"swap_endian":{"type":"boolean","description":"Swap Endianness of this index.","default":false},"signed":{"type":"boolean","description":"This index is signed or unsigned integer.","default":false}}}}}}}}}},"parameters":{"type":"array","title":"parameters","description":"List of Startup Parameters to be set before running ethercat instance.","items":{"type":"object","title":"startupParameters","required":["index","subindex","size","value"],"examples":[{"index":"0x8000","subindex":"0x04","size":32,"value":"0x55"}],"properties":{"index":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Startup Parameter's CoE index (in integer or hexadecimal string)."},"subindex":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Startup Parameter's CoE subindex (in integer or hexadecimal string)."},"size":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Size in bit (in integer or hexadecimal string)."},"value":{"type":["integer","string"],"pattern":"^0x[0-9a-fA-F]+","description":"Startup Parameter's value to be set (in integer or hexadecimal string)."}}}}}}}

=== STECHOQ/etherlab-nodejs/slaves.sample.json
[
	{
		"alias": 0,
		"position": 0,
		"vendor_id": "0x00000002",
		"product_code": "0x044c2c52"
	},

	{
		"alias": 0,
		"position": 1,
		"vendor_id": "0x00000002",
		"product_code": "0x0fa43052",

		"syncs": [
			{
				"index": 2,
				"watchdog_enabled": false,
				"pdos": [
					{
						"index": "0x1600",
						"entries": [
							{
								"index": "0x7000",
								"subindex": "0x01",
								"size": 16,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": true
							}
						]
					},

					{
						"index": "0x1601",
						"entries": [
							{
								"index": "0x7010",
								"subindex": "0x01",
								"size": 16,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": true
							}
						]
					},

					{
						"index": "0x1602",
						"entries": [
							{
								"index": "0x7020",
								"subindex": "0x01",
								"size": 16,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": true
							}
						]
					},

					{
						"index": "0x1603",
						"entries": [
							{
								"index": "0x7030",
								"subindex": "0x01",
								"size": 16,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": true
							}
						]
					}
				]
			}
		]
	},

	{
		"alias": 0,
		"position": 2,
		"vendor_id": "0x00000002",
		"product_code": "0x18503052",

		"syncs": [
			{
				"index": 2,
				"watchdog_enabled": false,
				"pdos": [
					{
						"index": "0x1600"
					},
					{
						"index": "0x1601"
					},
					{
						"index": "0x1602"
					},
					{
						"index": "0x1603"
					}
				]
			},

			{
				"index": 3,
				"watchdog_enabled": false,
				"pdos": [
					{
						"index": "0x1a00",
						"entries": [
							{
								"index": "0x6000",
								"subindex": "0x01",
								"size": 16,

								"add_to_domain": true,
								"swap_endian": true,
								"signed": false
							}
						]
					},

					{
						"index": "0x1a80",
						"entries": [
							{
								"index": "0xf100",
								"subindex": "0x01",
								"size": 8,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0xf100",
								"subindex": "0x02",
								"size": 8,

								"add_to_domain": false,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0xf100",
								"subindex": "0x03",
								"size": 8,

								"add_to_domain": false,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0xf100",
								"subindex": "0x04",
								"size": 8,

								"add_to_domain": false,
								"swap_endian": false,
								"signed": false
							}

						]
					},

					{
						"index": "0x1a81",
						"entries": [
							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 12,

								"add_to_domain": false,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0xf101",
								"subindex": "0x0d",
								"size": 1,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 2,

								"add_to_domain": false,
								"swap_endian": false,
								"signed": false
							},

							{
								"index": "0xf101",
								"subindex": "0x10",
								"size": 1,

								"add_to_domain": true,
								"swap_endian": false,
								"signed": false
							}
						]
					}
				]
			}
		],

		"parameters": [
			{
				"index": "0x8000",
				"subindex": "0x04",
				"size": 32,
				"value": "0x55"
			},
			{
				"index": "0x8000",
				"subindex": "0x05",
				"size": 32,
				"value": "0x014d"
			},
			{
				"index": "0x8000",
				"subindex": "0x20",
				"size": 8,
				"value": "0x11"
			},
			{
				"index": "0x8000",
				"subindex": "0x21",
				"size": 8,
				"value": "0x2b"
			},
			{
				"index": "0x8000",
				"subindex": "0x24",
				"size": 8,
				"value": "0xc3"
			},
			{
				"index": "0x8000",
				"subindex": "0x28",
				"size": 16,
				"value": "0x23"
			}
		]
	},

	{
		"alias": 0,
		"position": 3,
		"vendor_id": "0x00000002",
		"product_code": "0x0c663052",

		"syncs": [
			{
				"index": 3,
				"watchdog_enabled": false,
				"pdos": [
					{
						"index": "0x1a00",
						"entries": [
							{
								"index": "0x6000",
								"subindex": "0x01",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x02",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x03",
								"size": 2
							},

							{
								"index": "0x6000",
								"subindex": "0x05",
								"size": 2
							},

							{
								"index": "0x6000",
								"subindex": "0x07",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 5
							},

							{
								"index": "0x6000",
								"subindex": "0x0e",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x0f",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x10",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x11",
								"size": 16,

								"add_to_domain": true,
								"signed": false
							}
						]
					},

					{
						"index": "0x1a02",
						"entries": [
							{
								"index": "0x6010",
								"subindex": "0x01",
								"size": 1
							},

							{
								"index": "0x6010",
								"subindex": "0x02",
								"size": 1
							},

							{
								"index": "0x6010",
								"subindex": "0x03",
								"size": 2
							},

							{
								"index": "0x6010",
								"subindex": "0x05",
								"size": 2
							},

							{
								"index": "0x6010",
								"subindex": "0x07",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 5
							},

							{
								"index": "0x6010",
								"subindex": "0x0e",
								"size": 1
							},

							{
								"index": "0x6010",
								"subindex": "0x0f",
								"size": 1
							},

							{
								"index": "0x6010",
								"subindex": "0x10",
								"size": 1
							},

							{
								"index": "0x6010",
								"subindex": "0x11",
								"size": 16,

								"add_to_domain": true,
								"signed": false
							}
						]
					},

					{
						"index": "0x1a04",
						"entries": [
							{
								"index": "0x6020",
								"subindex": "0x01",
								"size": 1
							},

							{
								"index": "0x6020",
								"subindex": "0x02",
								"size": 1
							},

							{
								"index": "0x6020",
								"subindex": "0x03",
								"size": 2
							},

							{
								"index": "0x6020",
								"subindex": "0x05",
								"size": 2
							},

							{
								"index": "0x6020",
								"subindex": "0x07",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 5
							},

							{
								"index": "0x6020",
								"subindex": "0x0e",
								"size": 1
							},

							{
								"index": "0x6020",
								"subindex": "0x0f",
								"size": 1
							},

							{
								"index": "0x6020",
								"subindex": "0x10",
								"size": 1
							},

							{
								"index": "0x6020",
								"subindex": "0x11",
								"size": 16,

								"add_to_domain": true,
								"signed": false
							}
						]
					},

					{
						"index": "0x1a06",
						"entries": [
							{
								"index": "0x6030",
								"subindex": "0x01",
								"size": 1
							},

							{
								"index": "0x6030",
								"subindex": "0x02",
								"size": 1
							},

							{
								"index": "0x6030",
								"subindex": "0x03",
								"size": 2
							},

							{
								"index": "0x6030",
								"subindex": "0x05",
								"size": 2
							},

							{
								"index": "0x6030",
								"subindex": "0x07",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 1
							},

							{
								"index": "0x0000",
								"subindex": "0x00",
								"size": 5
							},

							{
								"index": "0x6030",
								"subindex": "0x0e",
								"size": 1
							},

							{
								"index": "0x6030",
								"subindex": "0x0f",
								"size": 1
							},

							{
								"index": "0x6030",
								"subindex": "0x10",
								"size": 1
							},

							{
								"index": "0x6030",
								"subindex": "0x11",
								"size": 16,

								"add_to_domain": true,
								"signed": false
							}
						]
					}
				]
			}
		]
	},

	{
		"alias": 0,
		"position": 4,
		"vendor_id": "0x00000002",
		"product_code": "0x0c663052",

		"syncs": [
			{
				"index": 3,
				"watchdog_enabled": false,
				"pdos": [
					{
						"index": "0x1a00",
						"entries": [
							{
								"index": "0x6000",
								"subindex": "0x01",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x02",
								"size": 1
							},

							{
								"index": "0x6000",
								"subindex": "0x03",
								"size": 2
